"""Fast local token measurement backed by the native tokm engine."""

from ._tokm import (
    ConfigurationError,
    CountResult,
    FileResult,
    InputError,
    LanguageResult,
    ScanFileResult,
    ScanResult,
    ScanTotals,
    SkipDetail,
    SkippedSummary,
    TextPolicy,
    TokenizerError,
    TokenizerMetadata,
    TokmError,
    __version__,
    count,
    count_file,
    scan,
)

__all__ = [
    "ConfigurationError",
    "CountResult",
    "FileResult",
    "InputError",
    "LanguageResult",
    "ScanFileResult",
    "ScanResult",
    "ScanTotals",
    "SkipDetail",
    "SkippedSummary",
    "TextPolicy",
    "TokenizerError",
    "TokenizerMetadata",
    "TokmError",
    "__version__",
    "count",
    "count_file",
    "scan",
]
